MeroRecipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("recipes.urls")),
    path("products/", include("products.urls")),
]

recipes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "recipe"

urlpatterns = [
    path("", views.LandingPage.as_view(), name="home"),
    path("share-recipe/", views.ShareRecipe.as_view(), name="share-recipe"),
    path("recipe-list/", views.RecipeListView.as_view(), name="recipe-list"),
    path("<int:pk>/", views.RecipeDetailView.as_view(), name="recipe-detail"),
    path("recipe-create/", views.RecipeCreateView.as_view(), name="recipe-create"),
    path(
        "<int:pk>/update/",
        views.RecipeUpdateView.as_view(),
        name="recipe-update",
    ),
    path("<int:pk>/delete/", views.RecipeDeleteView.as_view(), name="recipe-delete"),
    path("<int:pk>/rate/", views.RatingCreateView.as_view(), name="rate-recipe"),
    path(
        "<int:pk>/update-rating/",
        views.RatingUpdateView.as_view(),
        name="update-rating",
    ),
    path(
        "<int:pk>/delete-rating/",
        views.RatingDeleteView.as_view(),
        name="delete-rating",
    ),
]
# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home/header.html
 {% load static %}
 <!-- header -->
 <header id = "header" class = "vh-100 carousel slide" data-bs-ride = "carousel" style = "padding-top: 104px;">
    <div class = "container h-100 d-flex align-items-center carousel-inner">
        <div class = "text-center carousel-item active">
            <h2 class = "text-capitalize text-white">best collection</h2>
            <h1 class = "text-uppercase py-2 fw-bold text-white">new arrivals</h1>
            <a href = "#" class = "btn mt-3 text-uppercase">shop now</a>
        </div>
        <div class = "text-center carousel-item">
            <h2 class = "text-capitalize text-white">best price & offer</h2>
            <h1 class = "text-uppercase py-2 fw-bold text-white">new season</h1>
            <a href = "#" class = "btn mt-3 text-uppercase">buy now</a>
        </div>
    </div>

    <button class = "carousel-control-prev" type = "button" data-bs-target="#header" data-bs-slide = "prev">
        <span class = "carousel-control-prev-icon"></span>
    </button>
    <button class = "carousel-control-next" type = "button" data-bs-target="#header" data-bs-slide = "next">
        <span class = "carousel-control-next-icon"></span>
    </button>
</header>
<!-- end of header -->

templates/home/recipe-by-ratings.html
{% load static %}
<!-- special products -->
<section id="special" class="py-5">
    <div class="container">
        <div class="title text-center py-5">
            <h2 class="position-relative d-inline-block">From Our Shop</h2>
        </div>

        <div class="special-list row g-0">
            {% for product in special_products %}
            <div class="col-md-6 col-lg-4 col-xl-3 p-2">
                <div class="special-img position-relative overflow-hidden">
                    <img src="{{ product.image.url }}" class="w-100">
                    
                </div>
                <div class="text-center">
                    <p class="text-capitalize mt-3 mb-1">{{ product.name }}</p>
                    <span class="fw-bold d-block">Rs. {{ product.price }}</span>
                    <a href="#" class="btn btn-primary mt-3">Add to Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- end of special products -->

templates/home/show-recipes.html
{% load static %}
<!-- collection -->
<section id="collection" class="py-5">
    <div class="container">
        <div class="title text-center">
            <h2 class="position-relative d-inline-block">Recipe Collection</h2>
        </div>

        <div class="row g-0">

            <div class="collection-list mt-4 row gx-0 gy-3">
                {% for recipe in recipes %}
                <div class="col-md-6 col-lg-4 col-xl-3 p-2 best">
                    <div class="collection-img position-relative">
                        <a href="{% url 'recipe:recipe-detail' recipe.pk %}">
                            <img src="{{ recipe.image.url }}" alt="{{ recipe.recipe_name }}" class="img-fluid rounded " style="min-height: 300px; max-height: 300px; min-width: 250px; max-width: 250px;">
                        </a>
                    </div>
                    <div class="text-center">
                        <div class="rating mt-3">
                            <span class="text-warning">
                                {% for _ in recipe.rating %}
                                    <i class="fas fa-star"></i>
                                {% endfor %}
                            </span>
                        </div>
                        <p class="text-capitalize my-1">{{ recipe.recipe_name }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            
            <!-- Pagination links -->
            <div class="pagination mt-4">
                {% if recipes.has_previous %}
                    <a href="?page=1" class="page-link">&laquo; first</a>
                    <a href="?page={{ recipes.previous_page_number }}" class="page-link">previous</a>
                {% endif %}
            
                <span class="current-page">{{ recipes.number }}</span>
            
                {% if recipes.has_next %}
                    <a href="?page={{ recipes.next_page_number }}" class="page-link">next</a>
                    <a href="?page={{ recipes.paginator.num_pages }}" class="page-link">last &raquo;</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<!-- end of collection -->