MeroRecipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("recipes.urls")),
    path("products/", include("products.urls")),
]

recipes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "recipe"

urlpatterns = [
    path("", views.LandingPage.as_view(), name="home"),
    path("share-recipe/", views.ShareRecipe.as_view(), name="share-recipe"),
    path("recipe-list/", views.RecipeListView.as_view(), name="recipe-list"),
    path("<int:pk>/", views.RecipeDetailView.as_view(), name="recipe-detail"),
    path("recipe-create/", views.RecipeCreateView.as_view(), name="recipe-create"),
    path(
        "<int:pk>/update/",
        views.RecipeUpdateView.as_view(),
        name="recipe-update",
    ),
    path("<int:pk>/delete/", views.RecipeDeleteView.as_view(), name="recipe-delete"),
    path("<int:pk>/rate/", views.RatingCreateView.as_view(), name="rate-recipe"),
    path(
        "<int:pk>/update-rating/",
        views.RatingUpdateView.as_view(),
        name="update-rating",
    ),
    path(
        "<int:pk>/delete-rating/",
        views.RatingDeleteView.as_view(),
        name="delete-rating",
    ),
]
# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model


# Create your models here.


class Recipe(models.Model):
    DIFFICULTY_CHOICES = [
        ("Easy", "Easy"),
        ("Intermediate", "Intermediate"),
        ("Difficult", "Difficult"),
    ]

    recipe_name = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.TextField()
    instructions = models.TextField()
    cuisine = models.CharField(max_length=100)
    cooking_time = models.CharField(max_length=50)
    difficulty_level = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES)
    image = models.ImageField(upload_to="recipes/", blank=True, null=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.recipe_name


class Interaction(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)


class RecipeVisit(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


# For Image
@receiver(pre_delete, sender=Recipe)
def delete_recipe_image(sender, instance, **kwargs):
    # Check if the recipe has an associated image
    if instance.image:
        # Delete the image from the media storage
        instance.image.delete(save=False)


@receiver(pre_save, sender=Recipe)
def delete_previous_recipe_image(sender, instance, **kwargs):
    # Check if the instance is being updated and has a primary key (already saved in the database)
    if instance.pk and Recipe.objects.filter(pk=instance.pk).exists():
        # Retrieve the existing instance from the database
        existing_instance = Recipe.objects.get(pk=instance.pk)

        # Check if the image has changed (i.e., a new image has been uploaded)
        if instance.image and instance.image != existing_instance.image:
            # Delete the previous image
            existing_instance.image.delete(save=False)


# Connect the signal handlers to the respective signals
pre_delete.connect(delete_recipe_image, sender=Recipe)
pre_save.connect(delete_previous_recipe_image, sender=Recipe)


class Rating(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

recipes/forms.py
# recipes/forms.py
from django import forms
from django.forms import formset_factory
from .models import Recipe, Rating


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "recipe_name",
            "description",
            "cuisine",
            "cooking_time",
            "difficulty_level",
            "image",
            "ingredients",
            "instructions",
        ]

    ingredients = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 4}),
        help_text="Enter ingredients separated  by new lines (one step per line)",
    )

    instructions = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 4}),
        help_text="Enter instructions separated by new lines (one step per line)",
    )

    def clean_image(self):
        image = self.cleaned_data.get("image", False)
        if not image and self.instance:
            # If no new image is provided during update, return the current instance's image
            return self.instance.image
        return image


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["rating", "review"]
        widgets = {
            "rating": forms.RadioSelect(attrs={"class": "star-rating"}),
            "review": forms.Textarea(attrs={"rows": 4}),
        }

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import (
    View,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Recipe, Rating, Interaction
from django.core.paginator import Paginator
from .forms import RecipeForm, RatingForm
from django.db.models import Avg
from products.models import Product
from math import floor
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import pandas as pd
import numpy as np
from surprise import Reader, Dataset
from surprise.model_selection import train_test_split
from surprise import SVD, accuracy
from surprise.model_selection import cross_validate


# Create your views here.
class RecipeOwnerMixin(UserPassesTestMixin):
    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.user


class LandingPage(TemplateView, LoginRequiredMixin):
    model = Recipe
    template_name = "home.html"

    paginate_by = 12

    login_url = reverse_lazy("login")

    def handle_no_permission(self):
        return redirect(self.login_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fetch all recipes
        all_recipes = Recipe.objects.all()

        # Create a Paginator instance with 10 recipes per page
        paginator = Paginator(all_recipes, 10)

        # Get the current page number from the request's GET parameters
        page_number = self.request.GET.get("page")

        # Get the Page object for the current page
        page = paginator.get_page(page_number)

        context["recipes"] = page  # Pass the Page object to the template

        special_products = Product.objects.filter()[:4]  # Adjust the query as needed

        context["special_products"] = special_products
        return context


class ShareRecipe(LoginRequiredMixin, TemplateView):
    template_name = "recipe/share-recipe.html"
    login_url = reverse_lazy("login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context


class RecipeListView(LoginRequiredMixin, ListView, RecipeOwnerMixin):
    model = Recipe
    template_name = "recipe/recipe_list.html"
    context_object_name = "recipes"


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipe/recipe_form.html"
    form_class = RecipeForm
    success_url = reverse_lazy("recipe:recipe-list")

    def form_valid(self, form):
        form.instance.user = self.request.user  # Set the user to the logged-in user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView, UserPassesTestMixin):
    model = Recipe
    template_name = "recipe/recipe_form.html"
    form_class = RecipeForm
    success_url = reverse_lazy("recipe:recipe-list")

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.user

    def form_valid(self, form):
        recipe = form.save(commit=False)
        if not form.cleaned_data["image"]:
            # If image field is empty, retain the existing image
            recipe.image = self.get_object().image
        recipe.save()
        return super().form_valid(form)


class RecipeDetailView(LoginRequiredMixin, DetailView, UserPassesTestMixin):
    model = Recipe
    template_name = "recipe/recipe_detail.html"
    context_object_name = "recipe"

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.user

    def calculate_stars(self, rating):
        full_stars = int(rating)  # Take integer part
        decimal_part = rating - full_stars  # Calculate decimal part
        if decimal_part >= 0.75:
            full_stars += 1  # Round up to the nearest full star
            half_star = 0
        elif decimal_part >= 0.25:
            half_star = 1  # Use half star
        else:
            half_star = 0

        return full_stars, half_star

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.object
        recipes = list(Recipe.objects.all())
        user = self.request.user
        ratings = Rating.objects.all()

        try:
            user_rating = Rating.objects.get(recipe=recipe, user=user)
            context["rating"] = user_rating
        except Rating.DoesNotExist:
            context[
                "rating_form"
            ] = RatingForm()  # Replace with your actual rating form

        context["created_by"] = recipe.user
        context["review_count"] = Rating.objects.filter(recipe=recipe).count()
        context["average_rating"] = Rating.objects.filter(recipe=recipe).aggregate(
            Avg("rating")
        )["rating__avg"]

        average_rating_dict = Rating.objects.filter(recipe=recipe).aggregate(
            Avg("rating")
        )
        average_rating = average_rating_dict["rating__avg"]
        if average_rating is not None:
            full_stars, half_star = self.calculate_stars(average_rating)
        else:
            full_stars, half_star = 0, 0  # No ratings yet, set default values
        context["full_stars"] = full_stars
        context["half_star"] = half_star

        # algorithms
        # Collaborative Filtering
        # Extract features from all recipes

        ingredients = [recipe.ingredients for recipe in recipes]
        cuisines = [recipe.cuisine for recipe in recipes]
        difficulties = [recipe.difficulty_level for recipe in recipes]

        # Combine ingredients, cuisine, and difficulty into a single text-based feature
        features = [
            ingredients[i] + " " + cuisines[i] + " " + difficulties[i]
            for i in range(len(recipes))
        ]

        # Use TF-IDF Vectorization to convert features into numerical format
        tfidf_vectorizer = TfidfVectorizer()
        tfidf_matrix = tfidf_vectorizer.fit_transform(features)

        # Calculate cosine similarity between the current recipe and all other recipes
        cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

        # Get the index of the current recipe
        recipe_index = recipes.index(recipe)

        # Calculate similarity scores for all recipes
        similarity_scores = list(enumerate(cosine_sim[recipe_index]))

        # Sort recipes by similarity score (higher is more similar)
        similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

        # Get the top 5 recommended recipes (excluding the current recipe)
        recommendations = []
        for index, score in similarity_scores[1:4]:
            recommendations.append(recipes[index])

        context["recommendations"] = recommendations

        # NEXT ALGORITHM
        # recommend using  user-interaction
        # Load user-recipe interaction data from the Database
        # Retrieve all interactions for the user
        user_id = user.id
        interactions = Interaction.objects.filter(user=user)

        # Check if there are enough interactions for recommendations
        if interactions.count() < 2:
            context["not_enough_interactions"] = True
            return context

        # Create a DataFrame to hold the data
        data = {
            "user_id": [interaction.user.id for interaction in interactions],
            "recipe_id": [interaction.recipe.id for interaction in interactions],
            "rating": [interaction.rating for interaction in interactions],
        }

        df = pd.DataFrame(data)

        # Create a Surprise Reader object to specify the rating scale
        reader = Reader(rating_scale=(0, 5))

        # Load data into the Surprise dataset
        data = Dataset.load_from_df(df[["user_id", "recipe_id", "rating"]], reader)

        # Split data into train and test sets
        trainset, testset = train_test_split(data, test_size=0.2)

        # Build and train the model (SVD is used in this example)
        model = SVD()
        model.fit(trainset)

        # Make predictions on the test set
        test_predictions = model.test(testset)
        rmse = accuracy.rmse(test_predictions)

        # Example: Get top-N recommendations for a user
        user_id = user.id
        user_items = df[df["user_id"] == user_id]["recipe_id"]
        items_to_predict = [i for i in df["recipe_id"].unique() if i not in user_items]

        user_predictions = [
            (i, model.predict(user_id, i).est) for i in items_to_predict
        ]
        user_predictions.sort(key=lambda x: x[1], reverse=True)

        top_n = 5  # Number of recommendations to generate
        top_recommendations = user_predictions[:top_n]

        context["user_id"] = user_id
        context["top_recommendations"] = top_recommendations

        return context


class RecipeDeleteView(LoginRequiredMixin, DeleteView, RecipeOwnerMixin):
    model = Recipe
    template_name = "recipe/recipe_confirm_delete.html"
    success_url = reverse_lazy("recipe:recipe-list")
    context_object_name = "recipe:recipe-detail"


class RatingCreateView(LoginRequiredMixin, CreateView):
    model = Rating
    form_class = RatingForm
    template_name = (
        "recipe/recipe_detail.html"  # Use the same template as RecipeDetailView
    )

    def form_valid(self, form):
        recipe = get_object_or_404(Recipe, pk=self.kwargs["pk"])
        existing_rating = Rating.objects.filter(
            recipe=recipe, user=self.request.user
        ).first()

        if existing_rating:
            # User already submitted a rating and review, update them
            existing_rating.rating = form.cleaned_data["rating"]

templates/recipe/recipe_confirm_delete.html
<!-- recipes/recipe_confirm_delete.html -->
{% extends "_base.html" %}

{% block title %}Confirm Deletion{% endblock %}

{% block content %}
    <h1>Confirm Deletion</h1>
    <p>Are you sure you want to delete the recipe "{{ recipe.recipe_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger">
        <a href="{% url 'recipe:recipe-detail' recipe.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

templates/recipe/recipe_detail.html
<!-- recipe/recipe_detail.html -->
{% extends '_base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}{{ recipe.recipe_name }}{% endblock title %}

{% block content %}
<h1>{{ recipe.recipe_name }}</h1>
    <p>Description: {{ recipe.description }}</p>
    <p>Cuisine: {{ recipe.cuisine }}</p>
    <p>Cooking Time: {{ recipe.cooking_time }}</p>
    <p>Difficulty Level: {{ recipe.difficulty_level }}</p>

    <img src="{{ recipe.image.url }}" alt="{{ recipe.recipe_name }}" width="300">
    <h2>Ingredients:</h2>
    <ul>
        {% for ingredient in recipe.ingredients.splitlines %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </ul>
    <h2>Instructions:</h2>
    <ol>
        {% for instruction in recipe.instructions.splitlines %}
            <li>{{ instruction }}</li>
        {% endfor %}
    </ol>
    <p>Created By: {{ created_by.username }}</p>

<!-- Display the Rating Form -->
{% if rating %}
  <!-- Display Average Rating (if available) -->
  <h2>Reviews({{review_count}}):</h2>
  <p>Average Rating:{{ average_rating|floatformat:1 }}
   <span class="text-warning">
       {% for _ in full_stars|get_range %}
           <i class="fas fa-star"></i>
       {% endfor %}
       {% if half_star > 0 %}
           <i class="fas fa-star-half-alt"></i>
       {% endif %}
   </span>
  </p>


<!-- Display User's Rating Data -->
{% for rating in recipe.rating_set.all %}
   {% if rating.user == user %}
       <h2>Your Rating</h2>
       <p>{{ rating.user.username }}|{{ rating.created_at|date:"F d, Y"}}|{{ rating.created_at|time:"g:i A"}}</p>
       <p>Your Rating: <span class="text-warning">{% for _ in rating.rating|get_range %}<i class="fas fa-star"></i>{% endfor %}</span></p>
       <p>Your Review: {{ rating.review }}</p>
       <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateRecipeModal">
        Update Recipe
    </button>
    <!--For Update-->
<!-- Modal for updating the recipe -->
<div class="modal fade" id="updateRecipeModal" tabindex="-1" aria-labelledby="updateRecipeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateRecipeModalLabel">Update Recipe</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Your update form goes here -->
                <form method="post" action="{% url 'recipe:update-rating' recipe.pk %}">
                    {% csrf_token %}
                    <!-- Add form fields here -->
                    <!-- Display Stars for Rating -->
                    <div class="star-rating text-warning">
                        {% with num_stars=5 %}
                        {% for _ in num_stars|get_range %}
                        <label class="star" data-rating="{{ forloop.counter }}">
                            <i class="far fa-star"></i>
                        </label>
                        {% endfor %}
                        {% endwith %}
                    </div>

                    <!-- Pre-fill Rating Value -->
                    <input type="hidden" id="rating-input" name="rating" value="{{ rating.rating }}">

                    <!-- Review Textarea with Pre-filled Review -->
                    <div>
                        <label for="id_review">Your Review:</label><br>
                        <textarea id="id_review" name="review" rows="4" cols="50">{{ rating.review }}</textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>

    <a onclick="deleteRating({{ rating.pk }}, '{% url 'recipe:delete-rating' rating.pk %}');" class="btn btn-danger fa fa-trash-o">Delete</a>
   {% endif %}
{% endfor %}


{% elif rating_form%}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addRecipeModal">
    Rate Recipe
</button>
<!-- Add Recipe Modal -->
<div class="modal fade" id="addRecipeModal" tabindex="-1" aria-labelledby="addRecipeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addRecipeModalLabel">Rate Recipe</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Your add recipe form goes here -->
                <form method="post" action="{% url 'recipe:rate-recipe' recipe.pk %}">
                    {% csrf_token %}
                    <!-- Add form fields for recipe details here -->
                    <!-- Display Stars for Rating -->
                    <div class="star-rating text-warning">
                        {% with num_stars=5 %}
                            {% for _ in num_stars|get_range %}
                                <label class="star" data-rating="{{ forloop.counter }}">
                                    <i class="far fa-star"></i>
                                </label>
                            {% endfor %}
                        {% endwith %}
                    </div>

                    <input type="hidden" id="rating-input" name="rating" value="{{ rating.rating|default:0 }}">

                    <!-- Review Textarea -->
                    <div>
                        <label for="id_review">Your Review:</label><br>
                        <textarea id="id_review" name="review" rows="4" cols="50">
                            {{ rating.review|default_if_none:'' }}
                        </textarea>
                    </div>

                    <!-- ... Other form fields ... -->

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if rating %}
<!-- Display Other Ratings and Reviews -->
<h2>Other Ratings and Reviews</h2>
{% for rating in recipe.rating_set.all %}
   {% if rating.user != user %}
       <p>{{ rating.user.username }}|{{ rating.created_at|date:"F d, Y"}}|{{ rating.created_at|time:"g:i A"}}</p>
       <p>Rating: <span class="text-warning">{% for _ in rating.rating|get_range %}<i class="fas fa-star"></i>{% endfor %}</span></p>
       <p>Review: {{ rating.review }}</p>
   {% endif %}
{% endfor %}
{% endif %}


    {% if user.is_authenticated and user == created_by %}
    <!-- Link to Update Rating -->
    <a href="{% url 'recipe:recipe-update' recipe.pk %}">Edit Recipe</a>
    <a href="{% url 'recipe:recipe-delete' recipe.pk %}">Delete Recipe</a>
    {% endif %}
    <a href="{% url 'recipe:recipe-list' %}">Back to Recipe List</a>

<!-- Display Recommended Recipes -->
{% if recommendations %}
<div class="container mt-5">
    <h1 class="mb-4">Content-Based Recommendations for {{ recipe.recipe_name }}</h1>
    <div class="row">
        {% for recommended_recipe in recommendations %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <a href="{% url 'recipe:recipe-detail' recommended_recipe.pk %}">
                    <img src="{{ recommended_recipe.image.url }}" class="card-img-top" style="width: 300px; height: 275px;" alt="{{ recommended_recipe.recipe_name }}">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ recommended_recipe.recipe_name }}</h5>
                    <p class="card-text">{{ recommended_recipe.description }}</p>
                    
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endif %}


{% if not_enough_interactions %}
<p>Not enough interactions for recommendations.</p>
{% else %}
<h2>Top Recipe Recommendations</h2>
<ul>
  {% for recipe_id, rating in top_recommendations %}
    <li>
      <a href="{% url 'recipe:recipe-detail' recipe_id %}">
        Recipe ID: {{ recipe_id }} (Rating: {{ rating|floatformat:2 }})
      </a>
    </li>
  {% endfor %}
</ul>
{% endif %}


    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const stars = document.querySelectorAll('.star');
            const ratingInput = document.getElementById('rating-input');
            let currentRating = ratingInput.value;
    
            stars.forEach(function(star) {
                star.addEventListener('click', function() {
                    const ratingValue = parseInt(star.getAttribute('data-rating'));
                    ratingInput.value = ratingValue;
                    currentRating = ratingValue;
                    updateStarSelection(ratingValue);
                });
    
                star.addEventListener('mouseover', function() {
                    const ratingValue = parseInt(star.getAttribute('data-rating'));
                    updateStarSelection(ratingValue);
                });
    
                star.addEventListener('mouseout', function() {
                    updateStarSelection(currentRating);
                });
            });
    
            function updateStarSelection(selectedRating) {
                stars.forEach(function(star) {
                    const starRating = parseInt(star.getAttribute('data-rating'));
                    const starIcon = star.querySelector('i');
    
                    if (starRating <= selectedRating) {
                        starIcon.classList.remove('far');
                        starIcon.classList.add('fas');
                    } else {
                        starIcon.classList.remove('fas');
                        starIcon.classList.add('far');
                    }
                });
            }
    
            // Initialize star selection on page load
            updateStarSelection(currentRating);
        });

        //For deleting rating
        function deleteRating(ratingId, deleteUrl) {
            console.log('Delete function triggered with rating ID:', ratingId);
            if (confirm('Are you sure you want to delete this rating?')) {
                fetch(deleteUrl, {  // Use the deleteUrl passed from the template
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ rating_id: ratingId }),
                })
                .then(response => {
                    if (response.ok) {
                        // Reload the page or update the content as needed
                        location.reload();
                    } else {
                        // Handle error
                        console.error('Failed to delete rating');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            }
        }

        //for helpful
        
        
    </script>
{% endblock content %}

templates/recipe/recipe_form.html
<!-- recipes/recipe_form.html -->
{% extends '_base.html' %}

    {% block title %}{% if form.instance.pk %}Update Recipe{% else %}Create New Recipe{% endif %}{% endblock title %} 
{% block content %}
<h1>
    {% if request.resolver_match.url_name == 'recipe-create' %}
        Create New Recipe
    {% else %}
        Update Recipe
    {% endif %}
</h1>
<div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <form method="post" enctype="multipart/form-data" action="{% if recipe.id %}{% url 'recipe:recipe-update' recipe.id %}{% else %}{% url 'recipe:recipe-create' %}{% endif %}">
          {% csrf_token %}
          {{ form.as_p }}
          <!-- Add the IngredientFormSet and InstructionFormSet in the template -->

        <input type="submit" value="Save" class="btn btn-primary">
    </form>
    <a href="{% url 'recipe:recipe-list' %}">Back to Recipe List</a> 
      </div>
    </div>
  </div>

{% endblock content %}

templates/recipe/recipe_list.html
<!-- recipe/recipe_list.html -->
{% extends '_base.html' %}
{% block content %}
{% if user.is_authenticated %}

<h1>Recipe List</h1>
<ul class="list-group">
    {% for recipe in recipes %}
        <li class="list-group-item">
            <a href="{% url 'recipe:recipe-detail' recipe.pk %}"><img src="{{ recipe.image.url }}" alt="{{recipe.recipe_name}}" width="300" height="250"></a>
        </li>
    {% endfor %}
</ul>

{% endif %}

{% endblock content %}

templates/recipe/share-recipe.html
{% extends '_base.html' %}

{% block content %}
{% if user.is_authenticated %}
<h1>There goes the form for adding recipe.</h1>
{% else %}
<h1>Not Logged in.</h1>
{% endif %}

{% endblock content %}